<div class="row">
    <div class="col-sm-9">
        <h1>User Details</h1>
        <a href="/admin/user/index"><i class="fa fa-chevron-circle-left" aria-hidden="true"></i> Back to users</a>
    </div>
    <div class="col-sm-3 text-right">
        <br/>
        <a href="/admin/user/form?id=<?=$this->user->getId()?>" class="btn btn-emphasis">Edit</a>
    </div>
</div>
<hr/>

<div class="row">
    <div class="col-sm-3">
        <label>ID</label>
    </div>
    <div class="col-sm-9">
        <?=$this->user->getId()?>
    </div>
</div>

<div class="row">
    <div class="col-sm-3">
        <?=$this->formLabel($this->form->get('username'))?>
    </div>
    <div class="col-sm-5">
        <?=$this->user->getUsername()?>
    </div>
</div>

<!--div class="row">
    <div class="col-sm-3">
        <label>Password</label>
    </div>
    <div class="col-sm-9">
        <a class="btn btn-emphasis" href="/admin/user/change-password?id=<?=$this->user->getId()?>">Change Password</a>
    </div>
</div-->

<div class="row">
    <div class="col-sm-3">
        <?=$this->formLabel($this->form->get('email'))?>
    </div>
    <div class="col-sm-9">
        <?=$this->user->getEmail()?>
    </div>
</div>

<div class="row">
    <div class="col-sm-3">
        <?=$this->formLabel($this->form->get('displayName'))?>
    </div>
    <div class="col-sm-9">
        <?=$this->user->getDisplayName()?>
    </div>
</div>

<div class="row">
    <div class="col-sm-3">
        <?=$this->formLabel($this->form->get('type'))?>
    </div>
    <div class="col-sm-9">
        <?=$this->user->getType()?>
    </div>
</div>

<h2>User Status</h2>

<div class="row">
    <div class="col-sm-3">
        <?=$this->formLabel($this->form->get('state'))?>
    </div>
    <div class="col-sm-9">
        <?=$this->iconCheckMark($this->user->getState())?>
    </div>
</div>