<?php if(empty($this->id)): ?>
    <h1>Create User</h1>
<?php else: ?>
    <h1>Edit User <?=$this->entity->username?></h1>
<?php endif;?>

<?=$this->form()->openTag($this->form)?>

<?php if(empty($this->id)): ?>
    <a href="/admin/user/index"><i class="fa fa-chevron-circle-left" aria-hidden="true"></i> Back to users</a>
<?php else: ?>
    <a href="/admin/user/dashboard?id=<?=$this->id?>"><i class="fa fa-chevron-circle-left" aria-hidden="true"></i> Back to user dashboard</a>
<?php endif;?>

<h3>User Details</h3>
<div class="form-group">
    <div class="col-sm-3">
        <label>ID</label>
    </div>
    <div class="col-sm-9">
        <?=$this->user->getId()?>
        <?=$this->formHidden($this->form->get('id'))?>
    </div>
</div>

<div class="form-group">
    <div class="col-sm-3">
        <?=$this->formLabel($this->form->get('username'))?>
    </div>
    <div class="col-sm-9">
        <?=$this->formElement($this->form->get('username'))?>
    </div>
</div>
<?=$this->formElementErrors($this->form->get('username'),array('class'=>'help-inline form-errors'))?>

<div class="form-group">
    <div class="col-sm-3">
        <?=$this->formLabel($this->form->get('email'))?>
    </div>
    <div class="col-sm-9">
        <?=$this->formElement($this->form->get('email'))?>
    </div>
</div>
<?=$this->formElementErrors($this->form->get('email'),array('class'=>'help-inline form-errors'))?>

<div class="form-group">
    <div class="col-sm-3">
        <?=$this->formLabel($this->form->get('displayName'))?>
    </div>
    <div class="col-sm-4">
        <?=$this->formElement($this->form->get('displayName'))?>
    </div>
</div>
<?=$this->formElementErrors($this->form->get('displayName'),array('class'=>'help-inline form-errors'))?>

<div class="form-group">
    <div class="col-sm-3">
        <?=$this->formLabel($this->form->get('type'))?>
    </div>
    <div class="col-sm-4">
        <?=$this->formElement($this->form->get('type'))?>
    </div>
</div>
<?=$this->formElementErrors($this->form->get('type'),array('class'=>'help-inline form-errors'))?>

<h3>Password</h3>
<?php if($this->user->getId()): ?>
    <p>Leave this section alone unless you want to change the user's password</p>
<?php endif; ?>
<div class="form-group">
    <div class="col-sm-3">
        <?=$this->formLabel($this->form->get('password'))?>
    </div>
    <div class="col-sm-9">
        <?=$this->formElement($this->form->get('password'))?>
    </div>
</div>
<?=$this->formElementErrors($this->form->get('password'),array('class'=>'help-inline form-errors'))?>

<div class="form-group">
    <div class="col-sm-3">
        <?=$this->formLabel($this->form->get('password_confirm'))?>
    </div>
    <div class="col-sm-9">
        <?=$this->formElement($this->form->get('password_confirm'))?>
    </div>
</div>
<?=$this->formElementErrors($this->form->get('password_confirm'),array('class'=>'help-inline form-errors'))?>

<h3>User State</h3>
<div class="form-group">
    <div class="col-sm-3">
        <?=$this->formLabel($this->form->get('state'))?>
    </div>
    <div class="col-sm-9">
        <?=$this->formElement($this->form->get('state'))?>
    </div>
</div>
<?=$this->formElementErrors($this->form->get('state'),array('class'=>'help-inline form-errors'))?>

<button type="submit">Submit</button>

<?=$this->form()->closeTag($this->form)?>