<?=$this->partial('delamatre-zend-cms-admin/components/entity-index-header.phtml',array('routeName'=>$this->routeName,'name'=>'Users','recordCount'=>$this->recordCount))?>

<table class="table">
    <tr>
        <th>ID</th>
        <th>Username</th>
        <th>E-Mail</th>
        <th>Type</th>
        <th>State</th>
    </tr>
    <?php foreach($this->users as $user):
        /* @var \DelamatreZend\Entity\User $user */
        ?>
        <tr>
            <td><?=$user->getId()?></td>
            <td><a href="/admin/user/dashboard?id=<?=$user->getId()?>" target="_blank"><?=$user->getUsername()?></a></td>
            <td><?=$user->getEmail()?></td>
            <td><?=$user->getType()?></td>
            <td><?=$user->getState()?></td>
        </tr>
    <?php endforeach; ?>
</table>