<?=$this->partial('layout/components/banner.phtml',array('text'=>'Content Management System (CMS)','src'=>'applications.jpg'))?>

<div class="container">


    <div class="row">
        <div class="col-sm-9">
            <a href="/admin"><i class="fa fa-chevron-circle-left" aria-hidden="true"></i> Back to admin dashboard</a>
        </div>
    </div>


    <div class="row">
        <div class="col-sm-9">
            <h3>All Users</h3>
        </div>
        <div class="col-sm-3 text-right">
            <br/>
            <a href="/admin/user/form" class="btn btn-emphasis">Add New User</a>
        </div>
    </div>

    <table class="table">
        <tr>
            <th>ID</th>
            <th>Username</th>
            <th>E-Mail</th>
            <th>Type</th>
            <th>State</th>
        </tr>
        <?php foreach($this->users as $user):
            /* @var \DelamatreZend\Entity\User $user */
            ?>
            <tr>
                <td><?=$user->getId()?></td>
                <td><a href="/admin/user/dashboard?id=<?=$user->getId()?>" target="_blank"><?=$user->getUsername()?></a></td>
                <td><?=$user->getEmail()?></td>
                <td><?=$user->getType()?></td>
                <td><?=$user->getState()?></td>
            </tr>
        <?php endforeach; ?>
    </table>

</div>