<?php if(in_array($this->ZfcUserIdentity()->getType(),array('user','admin','superadmin'))): ?>

    <div class="col-sm-3 col-admin">
        <div class="panel-admin">
            <h2><a href="/admin/blog/index">Blog (<?=$this->blogCount?>)</a></h2>
            <p>Built-in blog.</p>
            <?php if(in_array($this->ZfcUserIdentity()->getType(),array('superadmin'))): ?>
                <!-- only show config to superadmins -->
                <a class="btn btn-primary" role="button" data-toggle="modal" href="#blogConfig" aria-expanded="false" aria-controls="blogConfig">
                    Config
                </a>
                <div class="modal fade" id="blogConfig" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h1 class="modal-title text-center" id="myModalLabel">Blog Config</h1>
                            </div>
                            <div class="modal-body">
                                Nothing to see here.
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div>
                </div>
            <?php endif; ?>
        </div>
    </div>

<?php endif; ?>