<?php if(in_array($this->ZfcUserIdentity()->getType(),array('user','admin','superadmin'))): ?>

    <div class="col-sm-3 col-admin">
        <div class="panel-admin">
            <h2><a href="/admin/filemanager/index">File Manager</a></h2>
            <p>Built-in file manager.</p>
            <?php if(in_array($this->ZfcUserIdentity()->getType(),array('superadmin'))): ?>
                <!-- only show config to superadmins -->
                <a class="btn btn-primary" role="button" data-toggle="modal" href="#filemanagerConfig" aria-expanded="false" aria-controls="filemanagerConfig">
                    Config
                </a>
                <div class="modal fade" id="filemanagerConfig" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h1 class="modal-title" id="myModalLabel">Elfinder Filemanager Config</h1>
                            </div>
                            <div class="modal-body">
                                <table class="table">
                                    <tr>
                                        <th>Debug</th>
                                        <td><?=$this->IconCheckMark($this->config()['filemanager']['debug'])?></td>
                                    </tr>
                                    <tr>
                                        <th>Base URL</th>
                                        <td><?=$this->config()['myapp']['baseurl']?></td>
                                    </tr>
                                    <tr>
                                        <th>Roots</th>
                                        <td>
                                            <ul class="list-unstyled">
                                                <?php foreach($this->config()['filemanager']['roots'] as $key=>$root): ?>
                                                    <li><?=$root['path']?> - <a href="<?=$this->config()['myapp']['baseurl'].$root['URL']?>" target="_blank"><?=$this->config()['myapp']['baseurl'].$root['URL']?></a> [<?=$root['driver']?>] </li>
                                                <?php endforeach; ?>
                                            </ul>
                                        </td>
                                    </tr>
                                </table>                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div>
                </div>
            <?php endif; ?>
        </div>
    </div>

<?php endif; ?>