<?php if(in_array($this->ZfcUserIdentity()->getType(),array('admin','superadmin'))): ?>

    <div class="col-sm-3 col-admin disabled">
        <div class="panel-admin">
            <h2><a href="/admin/gallery/index">Galleries (<?=$this->galleryCount?>)</a></h2>
            <p>Built-in dynamic galleries.</p>
            <?php if(in_array($this->ZfcUserIdentity()->getType(),array('superadmin'))): ?>
                <!-- only show config to superadmins -->
                <a class="btn btn-primary" role="button" data-toggle="collapse" href="#galleryConfig" aria-expanded="false" aria-controls="galleryConfig">
                    Config
                </a>
                <div class="modal fade" id="galleryConfig" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h1 class="modal-title" id="myModalLabel">Gallery Config</h1>
                            </div>
                            <div class="modal-body">
                                asd
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div>
                </div>
            <?php endif; ?>
        </div>
    </div>

<?php endif; ?>