<div class="section-admin">
    <h1>Content Management System (CMS)</h1>
    <p>Manage content w/ built-in WYSIWYG editor.</p>

    <!-- cms content -->
    <div class="row row-admin">
        <!-- blog -->
        <?php echo $this->partial('delamatre-zend-cms-admin/admin/navigation-components/blog.phtml'); ?>
        <!-- case studies -->
        <?php echo $this->partial('delamatre-zend-cms-admin/admin/navigation-components/case-study.phtml'); ?>
        <!-- content -->
        <?php echo $this->partial('delamatre-zend-cms-admin/admin/navigation-components/content.phtml'); ?>
        <!-- documents -->
        <?php echo $this->partial('delamatre-zend-cms-admin/admin/navigation-components/document.phtml'); ?>
        <!-- filemanager -->
        <?php echo $this->partial('delamatre-zend-cms-admin/admin/navigation-components/filemanager.phtml'); ?>
        <!-- gallery -->
        <?php echo $this->partial('delamatre-zend-cms-admin/admin/navigation-components/gallery.phtml'); ?>
        <!-- video -->
        <?php echo $this->partial('delamatre-zend-cms-admin/admin/navigation-components/video.phtml'); ?>
        <!-- whitepaper -->
        <?php echo $this->partial('delamatre-zend-cms-admin/admin/navigation-components/white-paper.phtml'); ?>
    </div><!-- end cms panels -->

</div><!-- end content management section -->