<?php if(in_array($this->ZfcUserIdentity()->getType(),array('admin','superadmin'))): ?>

<div class="col-sm-3 col-admin">
    <div class="panel-admin">
        <h2><a href="/admin/user/index">Users (<?=$this->userCount?>)</a></h2>
        <p>Manage users and access.</p>
        <?php if(in_array($this->ZfcUserIdentity()->getType(),array('superadmin'))): ?>
            <!-- only show config to superadmins -->
            <a class="btn btn-primary" role="button" data-toggle="collapse" href="#userConfig" aria-expanded="false" aria-controls="userConfig">
                Config
            </a>
            <div class="modal fade" id="userConfig" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h1 class="modal-title" id="myModalLabel">User Config</h1>
                        </div>
                        <div class="modal-body">
                            <table class="table">
                                <tr>
                                    <th>Enable Default Entities</th>
                                    <td><?=$this->iconCheckMark($this->config()['zfcuser']['enable_default_entities'])?></td>
                                </tr>
                                <tr>
                                    <th>Entity Class</th>
                                    <td><?=$this->config()['zfcuser']['user_entity_class']?></td>
                                </tr>
                                <tr>
                                    <th>Enable Registration</th>
                                    <td><?=$this->iconCheckMark($this->config()['zfcuser']['enable_registration'])?></td>
                                </tr>
                                <tr>
                                    <th>Login After Registration</th>
                                    <td><?=$this->iconCheckMark($this->config()['zfcuser']['login_after_registration'])?></td>
                                </tr>
                                <tr>
                                    <th>Registration Form CAPTCHA</th>
                                    <td><?=$this->iconCheckMark($this->config()['zfcuser']['use_registration_form_captcha'])?></td>
                                </tr>
                                <tr>
                                    <th>Enable Username</th>
                                    <td><?=$this->iconCheckMark($this->config()['zfcuser']['enable_username'])?></td>
                                </tr>
                                <tr>
                                    <th>Enable Displayname</th>
                                    <td><?=$this->iconCheckMark($this->config()['zfcuser']['enable_display_name'])?></td>
                                </tr>
                                <tr>
                                    <th>Auth Identity Fields</th>
                                    <td>
                                        <?php foreach($this->config()['zfcuser']['auth_identity_fields'] as $field):?>
                                            <?=$field?><br/>
                                        <?php endforeach; ?>
                                    </td>
                                </tr>
                                <tr>
                                    <th>Use Redirect Parameter If Present</th>
                                    <td><?=$this->iconCheckMark($this->config()['zfcuser']['use_redirect_parameter_if_present'])?></td>
                                </tr>
                                <tr>
                                    <th>Login Redirect Route</th>
                                    <td><?=$this->config()['zfcuser']['login_redirect_route']?></td>
                                </tr>
                                <tr>
                                    <th>Logout Redirect Route</th>
                                    <td><?=$this->config()['zfcuser']['logout_redirect_route']?></td>
                                </tr>
                                <tr>
                                    <th>Enable User State</th>
                                    <td><?=$this->iconCheckMark($this->config()['zfcuser']['enable_user_state'])?></td>
                                </tr>
                                <tr>
                                    <th>Default User State</th>
                                    <td><?=$this->iconCheckMark($this->config()['zfcuser']['default_user_state'])?></td>
                                </tr>
                                <tr>
                                    <th>Allowed Login States</th>
                                    <td>
                                        <?php foreach($this->config()['zfcuser']['allowed_login_states'] as $field):?>
                                            <?=$field?><br/>
                                        <?php endforeach; ?>
                                    </td>
                                </tr>
                            </table>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>
        <?php endif; ?>
    </div>
</div>

<?php endif; ?>