<?=$this->partial('layout/components/banner.phtml',array('text'=>'Filemanager','src'=>'applications.jpg'))?>
<div class="container">
    <div class="row">
        <div class="col-sm-4">
            <br/>
            <a href="/admin"><i class="fa fa-chevron-circle-left" aria-hidden="true"></i> Back to admin panel</a>
        </div>
        <div class="col-sm-8 text-right">
        </div>
    </div>
    <hr/>
    <div class="container">
        <div id="elfinder"></div>
    </div>
</div>
<style type="text/css">
    .elfinder-workzone{
        margin-top:25px;
    }
</style>
<script type="text/javascript">
    $(document).ready(function() {
        var options = {
            url  : '/admin/filemanager/connector',
            lang : 'en',
            width : 'auto',
            height : '500px',
            uiOptions : {

                // directories tree options
                tree : {
                    // expand current root on init
                    openRootOnLoad : false,
                    // auto load current dir parents
                    syncTree : true
                }

            }
        };
        $('#elfinder').elfinder(options);
    });
</script>