<h1>Log Files</h1>
<p>Browse the available log files.</p>
<div class="row">
    <div class="col-md-3">
        <h3>Browse Logs</h3>
        <ul class="">
            <?php foreach($this->logFiles as $logFile): ?>
                <li class="<?php if($this->read==$logFile){echo 'active';}?>">
                    <a href="/admin/settings/logs?read=<?=$logFile?>"><?=$logFile?> (<a href="/admin/settings/logs?download=<?=$logFile?>">download)</a></a>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
    <div class="col-md-9">
        <h3>Read Log</h3>
<textarea style="width:100%;height:600px;">
<?=$this->content?>
</textarea>
    </div>
</div>