<h1>Log Files</h1>
<p>Browse the available log files.</p>
<div class="row">
    <div class="col-md-3">
        <h2>Browse Logs</h2>
        <ul class="">
            <?php foreach($this->logFiles as $logFile): ?>
                <li class="<?php if($this->read==$logFile){echo 'active';}?>">
                    <a href="/admin/settings/logs?read=<?=$logFile?>"><?=$logFile?></a> (filesize=<?=filesize($logFile)?> <a href="/admin/settings/logs?download=<?=$logFile?>"><?=$this->icon('fa-download')?></a>)
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
    <div class="col-md-9">
        <div class="row">
            <div class="col-md-4">
                <h2>Read Log</h2>
            </div>
            <div class="col-md-8 text-right">
                <br/>
                <?php if($this->read): ?>
                <a href="/admin/settings/logs?clear=<?=$this->read?>&read=<?=$this->read?>" class="btn btn-danger">Clear Log</a>
                <a href="/admin/settings/logs?download=<?=$this->read?>" class="btn btn-primary"><?=$this->icon('fa-download')?> Download Log</a>
                <?php endif; ?>
            </div>
<textarea style="width:100%;height:600px;">
<?=$this->content?>
</textarea>
    </div>
</div>