<?=$this->partial('layout/components/banner.phtml',array('text'=>'Content Management System (CMS)','src'=>'applications.jpg'))?>

<div class="container">

    <?=$this->partial('delamatre-zend-cms-admin/components/entity-index-header.phtml',array('routeName'=>$this->routeName))?>

    <h1>All Galleries (<?=$this->recordCount?>)</h1>
    <p>These records are used to by build dynamic galleries. Each gallery item specifies a category which identifies the gallery that it is associated with.</p>
    <br/>

    <table class="table table-hover table-condensed">
        <tr>
            <th style="width:125px;">Thumb</th>
            <th>Category</th>
            <th>Key</th>
            <th>Title</th>
            <th>Link</th>
            <th style="width:150px;">Updated</th>
            <th  style="width:25px;"></th>
        </tr>
        <?php foreach($this->records as $record):
            /* @var \Application\Entity\CaseStudy $record */
            ?>
            <tr class="<?php if($record->active==false){echo 'danger';}?>">
                <td><img src="<?=$record->getImageThumb()?>" title="<?=$record->title?>" class="img-responsive" /></td>
                <td><?=$record->category?></td>
                <td><?=$record->key?></td>
                <td><?=$record->title?></td>
                <td><?=$record->link?></td>
                <td>
                    <?php if($record->updated_datetime): ?>
                        <?=$record->updated_datetime->format($this->config()['myapp']['datetime_format'])?>
                    <?php endif; ?>
                </td>
                <td><a href="/admin/<?=$this->routeName?>/form?id=<?=$record->id?>"><?=$this->icon('fa-pencil-square','fa-lg')?></a></td>
            </tr>
        <?php endforeach; ?>
    </table>

</div>