<?=$this->partial('delamatre-zend-cms-admin/components/entity-index-header.phtml',array('routeName'=>$this->routeName,'name'=>'E-Mail Template','recordCount'=>$this->recordCount))?>

<table class="table table-hover table-condensed">
    <tr>
        <th style="width:125px;">Key</th>
        <th style="width:200px;">Title</th>
        <th>Description</th>
        <th style="width:150px;">Updated</th>
        <th  style="width:25px;"></th>
    </tr>
    <?php foreach($this->records as $record):
        /* @var \Application\Entity\CaseStudy $record */
        ?>
        <tr class="<?php if($record->active==false){echo 'danger';}?>">
            <td><?=$record->key?></td>
            <td><?=$record->title?></td>
            <td><?=$record->description?></td>
            <td>
                <a href="/admin/email-template/preview?id=<?=$record->id?>" target="_blank">Preview</a>
            </td>
            <td><a href="/admin/<?=$this->routeName?>/form?id=<?=$record->id?>"><?=$this->icon('fa-pencil-square','fa-lg')?></a></td>
        </tr>
    <?php endforeach; ?>
</table>