<div class="container">

    <div class="section-admin">
        <h1>Sight Source</h1>
        <p>Manage Sight Source objects.</p>

        <!-- sight source admin -->
        <div class="row row-admin">
            <!-- surgeries -->
           <?php echo $this->partial('delamatre-zend-cms-admin/admin/navigation-components/surgery.phtml'); ?>
            <!-- patients -->
           <?php echo $this->partial('delamatre-zend-cms-admin/admin/navigation-components/patient.phtml'); ?>
        </div><!-- end cms panels -->

    </div><!-- end sight source admin -->

    <div class="section-admin">
        <h1>Content Management System (CMS)</h1>
        <p>Manage content w/ built-in WYSIWYG editor.</p>

        <!-- cms content -->
        <div class="row row-admin">
            <!-- blog -->
            <?php echo $this->partial('delamatre-zend-cms-admin/admin/navigation-components/blog.phtml'); ?>
            <!-- content -->
            <?php echo $this->partial('delamatre-zend-cms-admin/admin/navigation-components/content.phtml'); ?>
            <!-- filemanager -->
            <?php echo $this->partial('delamatre-zend-cms-admin/admin/navigation-components/filemanager.phtml'); ?>
            <!-- gallery -->
            <?php echo $this->partial('delamatre-zend-cms-admin/admin/navigation-components/gallery.phtml'); ?>
        </div><!-- end cms panels -->

    </div><!-- end content management section -->

    <?php if(in_array($this->ZfcUserIdentity()->getType(),array('admin','superadmin'))): ?>

    <div class="section-admin">
        <h1>Security</h1>
        <p>Manage security for the site.</p>

        <!-- security section -->
        <div class="row row-admin">

            <!-- users -->
            <?php echo $this->partial('delamatre-zend-cms-admin/admin/navigation-components/user.phtml'); ?>
            <!-- organizations -->
            <?php echo $this->partial('delamatre-zend-cms-admin/admin/navigation-components/organization.phtml'); ?>

        </div>

    </div>
    <?php endif; ?>

</div>