<?=$this->partial('delamatre-zend-cms-admin/components/entity-index-header.phtml',array('routeName'=>$this->routeName,'name'=>'Organization','recordCount'=>$this->recordCount,'key'=>$this->entity->name))?>

<table class="table">
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Type</th>
        <th>State</th>
        <th></th>
    </tr>
    <?php foreach($this->records as $organization):
        /* @var \DelamatreZend\Entity\Organization $organization */
        ?>
        <tr>
            <td><?=$organization->id?></td>
            <td><?=$organization->name?></td>
            <td><?=$organization->type?></td>
            <td><?=$this->iconCheckMark($organization->state)?></td>
            <td><a href="/admin/organization/dashboard?id=<?=$organization->id?>" class="img-responsive"><?=$this->icon('fa-pencil-square','fa-lg')?></a></td>
        </tr>
    <?php endforeach; ?>
</table>