<?php if(empty($this->id)): ?>
    <h1>Create Blog Post</h1>
<?php else: ?>
    <h1>Edit Blog Post <?=$this->entity->key?></h1>
<?php endif;?>

<?=$this->form()->openTag($this->form->setAttribute('onsubmit','return postForm();'))?>

<div class="row">
    <div class="col-sm-4">
        <br/>
        <a href="/admin/<?=$this->routeName?>/index"><i class="fa fa-chevron-circle-left" aria-hidden="true"></i> Back to admin</a>
    </div>
    <div class="col-sm-8 text-right">
        <?php if($this->entity->id): ?>
            <?php if($this->entity->active==true): ?>
                <a class="btn btn-danger" href="/admin/<?=$this->routeName?>/deactivate?id=<?=$this->entity->id?>">Deactivate</a>
            <?php else: ?>
                <a class="btn btn-success" href="/admin/<?=$this->routeName?>/activate?id=<?=$this->entity->id?>">Activate</a>
            <?php endif; ?>
        <?php endif; ?>
        <button class="btn btn-primary" type="submit">Save Content</button>
    </div>
</div>

<hr/>

<?php if($this->entity->id && $this->entity->active==false): ?>
    <div class="alert alert-danger">
        <p>This record is inactive. Click `Activate` above to activate this record.</p>
    </div>
<?php endif; ?>

<!-- tab navigation -->
<ul class="nav nav-tabs nav-tabs-admin" role="tablist">
    <li role="presentation" class="<?php if(!$this->defaultTab || $this->defaultTab=='content-details'){echo 'active';} ?>">
        <a href="#content-details" aria-controls="lead-details" role="tab" data-toggle="tab">Content Details</a>
    </li>
    <li role="presentation" class="<?php if($this->defaultTab=='meta-data'){echo 'active';} ?>">
        <a href="#meta-data" aria-controls="analytics" role="tab" data-toggle="tab">Meta Data</a>
    </li>
    <li role="presentation" class="<?php if($this->defaultTab=='content-other'){echo 'active';} ?>">
        <a href="#content-other" aria-controls="analytics" role="tab" data-toggle="tab">Other</a>
    </li>
</ul>

<!-- tab content -->
<div class="tab-content tab-content-admin">

    <!-- tab : content details -->
    <div role="tabpanel" class="tab-pane <?php if(!$this->defaultTab || $this->defaultTab=='content-details'){echo 'active';} ?>" id="content-details">

        <div style="margin:0 25px 0 25px;">
            <?=$this->formRow($this->form->get('key'))?>
            <?=$this->formRow($this->form->get('title'))?>
            <?=$this->formRow($this->form->get('category'))?>
            <?php //$this->formRow($this->form->get('contentType'))?>
        </div>

    </div>

    <!-- tab : meta data -->
    <div role="tabpanel" class="tab-pane <?php if($this->defaultTab=='meta-data'){echo 'active';} ?>" id="meta-data">

        <div class="alert">
            <p>Meta data is used to describe this data to browsers and search engines.</p>
        </div>

        <div style="margin:0 25px 0 25px;">

            <?=$this->formRow($this->form->get('description'))?>
            <?=$this->formRow($this->form->get('keywords'))?>
        </div>

    </div>

    <!-- tab : other -->
    <div role="tabpanel" class="tab-pane <?php if($this->defaultTab=='content-other'){echo 'active';} ?>" id="content-other">

        <div style="margin:0 25px 0 25px;">
            <?=$this->formElfinder($this->form->get('image'))?>
            <?=$this->formElfinder($this->form->get('imageThumb'))?>
            <?=$this->formRow($this->form->get('imageMenu'))?>
            <?=$this->formRow($this->form->get('descriptionMenu'))?>
        </div>

    </div>

</div><!-- end: tab content -->

<h2>Content Short</h2>
<?=$this->partial('delamatre-zend-cms-admin/components/wysiwyg.phtml',array('content'=>$this->entity->contentShort,'formElement'=>$this->form->get('contentShort'),'id'=>'summernote-content-short','buildPostFormFunction'=>false))?>

<h2>Content</h2>
<?=$this->partial('delamatre-zend-cms-admin/components/wysiwyg.phtml',array('content'=>$this->entity->content,'formElement'=>$this->form->get('content'),'id'=>'summernote-content','buildPostFormFunction'=>false))?>


<script type="text/javascript">

    var postForm = function() {
        var content = $('#content').val($('#summernote-content').summernote('code'));
        var contentShort = $('#contentShort').val($('#summernote-content-short').summernote('code'));
    }

</script>


<?=$this->form()->closeTag($this->form)?>