<?=$this->partial('layout/components/banner.phtml',array('text'=>'Content Management System (CMS)','src'=>'applications.jpg'))?>

<div class="container">

    <?=$this->partial('delamatre-zend-cms-admin/components/entity-index-header.phtml',array('routeName'=>$this->routeName))?>

    <h1>All Blog Posts (<?=$this->recordCount?>)</h1>
    <p>Built-in blog system for CMS.</p>
    <br/>

    <table class="table table-hover table-condensed">
        <tr>
            <th style="width: 125px;">Image</th>
            <th style="width:200px;">Key</th>
            <th>Title</th>
            <th style="width:150px;">Category</th>
            <th style="width:150px;">Updated</th>
            <th></th>
        </tr>
        <?php foreach($this->records as $record):
            /* @var \DelamatreZendCms\Entity\Blog $record */
            ?>
            <tr class="<?php if($record->active==false){echo 'danger';}?>">
                <td><img src="<?=$record->getImageThumb()?>" title="<?=$record->title?>" class="img-responsive" /></td>
                <td><?=$record->key?></td>
                <td><?=$record->title?></td>
                <td><?=$record->category?></td>
                <td>
                    <?php if($record->posted_timestamp): ?>
                        <?=$record->posted_timestamp->format($this->config()['myapp']['datetime_format'])?>
                    <?php endif; ?>
                </td>
                <td><a href="/admin/<?=$this->routeName?>/form?id=<?=$record->id?>" class="img-responsive"><?=$this->icon('fa-pencil-square','fa-lg')?></a></td>
            </tr>
        <?php endforeach; ?>
    </table>

</div>