<?=$this->form()->openTag($this->form)?>

<div class="row">
    <div class="col-sm-9">
        <br/>
        <a href="/admin/<?=$this->routeName?>/form?id=<?=$this->entity->id?>&default-tab=content-applications"><i class="fa fa-chevron-circle-left" aria-hidden="true"></i> Back to <?=$this->entity->title?></a>
    </div>
    <div class="col-sm-3 text-right">
    </div>
</div>

<hr/>

<h1>Choose Application</h1>

<?=$this->formHidden($this->form->get('id'))?>
<?=$this->formLabel($this->form->get('application'))?>
<?=$this->formSelect($this->form->get('application'))?>

<button type="submit">Add</button>

<?=$this->form()->closeTag($this->form)?>