<?=$this->partial('layout/components/banner.phtml',array('text'=>'Add New White Paper To '.$this->entity->title,'src'=>'applications.jpg'))?>

<div class="container">

    <?=$this->form()->openTag($this->form)?>

    <div class="row">
        <div class="col-sm-9">
            <br/>
            <a href="/admin/<?=$this->routeName?>/form?id=<?=$this->entity->id?>&default-tab=content-white-papers"><i class="fa fa-chevron-circle-left" aria-hidden="true"></i> Back to <?=$this->entity->title?></a>
        </div>
        <div class="col-sm-3 text-right">
        </div>
    </div>

    <hr/>
    <div class="container">

        <h1>Choose White Paper</h1>

        <?=$this->formHidden($this->form->get('id'))?>
        <?=$this->formLabel($this->form->get('white-paper'))?>
        <?=$this->formSelect($this->form->get('white-paper'))?>

        <button type="submit">Add</button>

    </div>

    <?=$this->form()->closeTag($this->form)?>
</div>