<?=$this->form()->openTag($this->form)?>

<h1>Choose Product Category</h1>

<div class="row">
    <div class="col-sm-9">
        <br/>
        <a href="/admin/<?=$this->routeName?>/form?id=<?=$this->entity->id?>&default-tab=product-details"><i class="fa fa-chevron-circle-left" aria-hidden="true"></i> Back to <?=$this->entity->title?></a>
    </div>
    <div class="col-sm-3 text-right">
    </div>
</div>

<hr/>

<?=$this->formHidden($this->form->get('id'))?>

<div class="row form-row">
    <div class="col-md-4">
        <?=$this->formRow($this->form->get('product-category'))?>
    </div>
</div>

<button type="submit" class="btn btn-primary">Add</button>

<?=$this->form()->closeTag($this->form)?>