<div class="row">
    <div class="col-sm-4">
        <br/>
        <a href="/admin/<?=$this->routeName?>/index"><i class="fa fa-chevron-circle-left" aria-hidden="true"></i> Back to records</a>
    </div>
    <div class="col-sm-8 text-right">
        <?php if($this->entity->id): ?>
            <?php if($this->entity->active==true): ?>
                <a class="btn btn-danger" href="/admin/<?=$this->routeName?>/deactivate?id=<?=$this->entity->id?>">Deactivate</a>
            <?php else: ?>
                <a class="btn btn-success" href="/admin/<?=$this->routeName?>/activate?id=<?=$this->entity->id?>">Activate</a>
            <?php endif; ?>
        <?php endif; ?>
        <button class="btn btn-primary" type="submit">Save Record</button>
    </div>
</div>

<hr/>