<div class="row">
    <div class="col-sm-9">
        <h1><?=$this->name?> (<?=$this->recordCount?>)</h1>
        <!--a href="/admin"><i class="fa fa-chevron-circle-left" aria-hidden="true"></i> Back to admin dashboard</a-->
    </div>
    <div class="col-sm-3 text-right">
        <br/>
        <a href="/admin/<?=$this->routeName?>/form" class="btn btn-emphasis">Add New</a>
    </div>
</div>

<hr/>