<?=$this->partial('delamatre-zend-cms-admin/components/entity-index-header.phtml',array('routeName'=>$this->routeName,'name'=>'Videos','recordCount'=>$this->recordCount))?>

<table class="table table-hover table-condensed">
    <tr>
        <th style="width:125px;">Thumb</th>
        <th style="width:200px;">Key</th>
        <th>Title</th>
        <th>Youtube URL</th>
        <th  style="width:150px;">Display On Web</th>
        <th style="width:150px;">Updated</th>
        <th  style="width:25px;"></th>
    </tr>
    <?php foreach($this->records as $record):
        /* @var \Application\Entity\CaseStudy $record */
        ?>
        <tr class="<?php if($record->active==false){echo 'danger';}?>">
            <td><img src="<?=$record->getImageThumb()?>" title="<?=$record->title?>" class="img-responsive" /></td>
            <td><?=$record->key?></td>
            <td><?=$record->title?></td>
            <td><?=$record->youtubeUrl?></td>
            <td><?=$this->iconCheckMark($record->display_on_website)?></td>
            <td>
                <?php if($record->updated_datetime): ?>
                    <?=$record->updated_datetime->format($this->config()['myapp']['datetime_format'])?>
                <?php endif; ?>
            </td>
            <td><a href="/admin/<?=$this->routeName?>/form?id=<?=$record->id?>"><?=$this->icon('fa-pencil-square','fa-lg')?></a></td>
        </tr>
    <?php endforeach; ?>
</table>