<?php

if(isset($_GET['category'])){
    $this->category = $_GET['category'];
}else{
    $this->category = null;
}

//groups the e-mails by category
$grouped = array();
/* @var \DelamatreZendCms\Entity\Document $record */
foreach($this->records as $record) {
    $grouped[$record->category][] = $record;
}

$additionalActions = '';
?>

<?=$this->partial('delamatre-zend-cms-admin/components/entity-index-header.phtml',array('routeName'=>$this->routeName,'name'=>'Videos','recordCount'=>$this->recordCount))?>

<?php if(!empty($this->category)): ?>
    <div class="alert alert-info">
        You are looking at records for category <?=$this->category?> only. <a href="/admin/<?=$this->routeName?>/index">View all records</a>.
    </div>
<?php endif; ?>

<?php foreach($grouped as $category=>$records):?>
    <h2 class="cms-thumbnail-row-title"><a href="/admin/<?=$this->routeName?>/index?category=<?=$category?>"><?=$category?></a></h2>
    <hr/>
    <div class="row cms-thumbnail-row">
    <?php $i=0;foreach($records as $record):$i++; ?>
        <div class="col-md-2 cms-thumbnail <?php if($record->display_on_website==false){echo'alert-warning';} ?> <?php if($record->active==false){echo'alert-danger';} ?>">
            <h4><?=$record->title?>&nbsp;<a href="<?=$record->getUrl()?>" target="_blank"><?=$this->icon('fa-youtube')?></h4>
            <a href="/admin/<?=$this->routeName?>/form?id=<?=$record->id?>"><img src="<?=$record->getImageThumb()?>" title="<?=$record->title?>" class="img-responsive" /></a>
        </div>
        <?php if($i==6):$i=0; ?>
            </div>
            <div class="row">
        <?php endif; ?>
    <?php endforeach; ?>
    </div>
<?php endforeach ; ?>
