<?php

if(isset($_GET['category'])){
    $this->category = $_GET['category'];
}else{
    $this->category = null;
}

//groups the e-mails by category
$grouped = array();
/* @var \DelamatreZendCms\Entity\Document $record */
foreach($this->records as $record) {
    $grouped[$record->category][] = $record;
}

$additionalActions = '';
?>

<?=$this->partial('delamatre-zend-cms-admin/components/entity-index-header.phtml',array('routeName'=>$this->routeName,'name'=>'Videos','recordCount'=>$this->recordCount))?>

<?php foreach($grouped as $category=>$records):?>
    <h2><?=$category?></h2>
    <hr/>
    <div class="row">
    <?php $i=0;foreach($records as $record):$i++; ?>
        <div class="col-md-2">
            <h4><?=$record->title?></h4>
            <a href="/admin/<?=$this->routeName?>/form?id=<?=$record->id?>"><img src="<?=$record->getImageThumb()?>" title="<?=$record->title?>" class="img-responsive" /></a>
        </div>
        <?php if($i==6):$i=0; ?>
            </div>
            <div class="row">
        <?php endif; ?>
    <?php endforeach; ?>
    </div>
<?php endforeach ; ?>