<?php echo $this->doctype(); ?>
<html lang="en">
<head>
<meta charset="utf-8">
<link rel="icon" href="/favicon.ico" type="image/x-icon"/>
<?php echo $this->headTitle($this->config()['myapp']['appendTitle'])->setSeparator(' - ')->setAutoEscape(false); ?>
<?php echo $this->headMeta()
    ->appendName('viewport', 'width=device-width, initial-scale=1.0')
    ->appendHttpEquiv('X-UA-Compatible', 'IE=edge'); ?>
<?php echo $this->headLink(); ?>
<?php echo $this->headStyle(); ?>
<?php echo $this->headScript(); ?>
<?php echo $this->inlineScript() ?>
<?php echo $this->adobeTypeKit()?>
<?php echo $this->googleAnalytics(null,null,array('1'=>session_id(),'2'=>$this->IPAddress())); ?>
</head>
<?php if($this->zfcUserIdentity()
&& $this->config()['myapp']['environment']['type']!=ENVIRONMENT_TYPE_PRODUCTION): ?>
    <body class="wf-loading body-adjust">
<?php else: ?>
    <body class="wf-loading">
<?php endif; ?>

    <?php if($this->zfcUserIdentity()
        && $this->config()['myapp']['environment']['type']!=ENVIRONMENT_TYPE_PRODUCTION): ?>

        <!-- environment / user notification -->
        <div class="environment alert alert-warning">

            <div class="row">
                <div class="col-sm-6">
                    <?php if($this->config()['myapp']['environment']['type']!=ENVIRONMENT_TYPE_PRODUCTION ):?>
                        This is a <?=$this->config()['myapp']['environment']['type']?> environment. Notes: <?=$this->config()['myapp']['environment']['notes']?>
                    <?php endif; ?>
                </div>
                <div class="col-sm-6 text-right">
                    <?php if($this->zfcUserIdentity()):?>
                        Logged in as  <?=$this->zfcUserDisplayNAme()?> <span class="text-muted">[<?=$this->zfcUserIdentity()->getType()?>]</span> <a href="/user/logout">Logout</a>
                    <?php else: ?>
                        <a href="/user/login">Login</a>
                    <?php endif; ?>
                </div>
            </div>

        </div>

    <?php endif; ?>

    <?php if($this->zfcUserIdentity()
    && $this->config()['myapp']['environment']['type']!=ENVIRONMENT_TYPE_PRODUCTION): ?>
        <nav class="navbar navbar-inverse navbar-fixed-top environment-adjust">
    <?php else: ?>
        <nav class="navbar navbar-inverse navbar-fixed-top">
    <?php endif; ?>

        <div class="container-fluid">
            <div class="navbar-header">
                <!--button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">
                        <h1>Toggle navigation</h1>
                    </span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button-->
                <!--a class="navbar-brand" href="/admin">
                    <img src="<?=$this->config()['myapp']['logo']?>" style="max-height:72px;padding:5px;" />
                </a-->
                <a class="navbar-brand" href="/admin">
                    <h1><?=$this->config()['myapp']['name']?> Dashboard</h1>
                </a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <!--ul class="nav navbar-nav navbar-right">
                    <li><a href="#">Dashboard</a></li>
                    <li><a href="#">Settings</a></li>
                    <li><a href="#">Profile</a></li>
                    <li><a href="#">Help</a></li>
                </ul-->
            </div>
        </div>
    </nav>

    <!-- navigation -->
    <?php //echo $this->navigation('default')->menu()->setPartial(array('layout/navigation/menu.phtml','default'))->render(); ?>

    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-3 col-md-2 sidebar">
                <h3>Overview</h3>
                <ul class="nav nav-sidebar">
                    <li><a href="/admin">Dashboard</a></li>
                </ul>
                <hr/>
                <h3>Marketing</h3>
                <!--h4>&nbsp;&nbsp;Leads</h4-->
                <ul class="nav nav-sidebar">
                    <li><a href="/admin/lead/index">Leads Dashboard</a></li>
                </ul>
                <!--h4>&nbsp;&nbsp;ROI Calculations</h4-->
                <ul class="nav nav-sidebar">
                    <li><a href="/admin/roi-calculator/index">ROI Calculations Dashboard</a></li>
                </ul>
                <hr/>
                <h3>Content Management System</h3>
                <h4>&nbsp;&nbsp;Custom Objects</h4>
                <ul class="nav nav-sidebar">
                    <li><a href="/admin/application/index">Applications</a></li>
                    <li><a href="/admin/industry/index">Industries</a></li>
                    <li><a href="/admin/service/index">Services</a></li>
                    <li><a href="/admin/technology/index">Technologies</a></li>
                </ul>
                <h4>&nbsp;&nbsp;Built-in Objects</h4>
                <ul class="nav nav-sidebar">
                    <li><a href="/admin/blog/index">Blog</a></li>
                    <li><a href="/admin/case-study/index">Case Studies</a></li>
                    <li><a href="/admin/content/index">Content</a></li>
                    <li><a href="/admin/document/index">Documents</a></li>
                    <li><a href="/admin/gallery/index">Galleries</a></li>
                    <li><a href="/admin/video/index">Videos</a></li>
                    <li><a href="/admin/white-paper/index">White Papers</a></li>
                </ul>
                <hr/>
                <h3>Security</h3>
                <ul class="nav nav-sidebar">
                    <li><a href="/admin/user/index">Users</a></li>
                    <!--li><a href="/admin/organization/index">Organizations</a></li-->
                </ul>
                <hr/>
                <h3>System</h3>
                <h4>&nbsp;&nbsp;Tools</h4>
                <ul class="nav nav-sidebar">
                    <li><a href="/admin/filemanager/index">Filemanager</a></li>
                </ul>
                <h4>&nbsp;&nbsp;Settings</h4>
                <ul class="nav nav-sidebar">
                    <li><a href="/admin/settings/configuration">Configuration</a></li>
                    <li><a href="/admin/settings/logs">Logs</a></li>
                </ul>
                <hr/>
                <h3>Help</h3>
                <ul class="nav nav-sidebar">
                    <li><a href="/admin/help/content">Content Creator's Cheat Sheet</a></li>
                </ul>
            </div>
            <div class="col-sm-9 col-md-10">

                <!-- content -->
                <?php echo $this->content; ?>

            </div>
        </div>
    </div>

</body>
</html>