<?=$this->partial('delamatre-zend-cms-admin/components/entity-index-header.phtml',array('routeName'=>$this->routeName,'name'=>'White Papers','recordCount'=>$this->recordCount))?>

<table class="table table-hover table-condensed">
    <tr>
        <th style="width:200px;">Key</th>
        <th>Title</th>
        <th style="width:200px;">Preview</th>
        <th style="width:150px;">Updated</th>
        <th  style="width:25px;"></th>
    </tr>
    <?php foreach($this->records as $record):
        /* @var \Application\Entity\CaseStudy $record */
        ?>
        <tr class="<?php if($record->display_on_website==false){echo'alert-warning';} ?> <?php if($record->active==false){echo'alert-danger';} ?>">
            <td><?=$record->key?></td>
            <td><?=$record->title?></td>
            <td></td>
            <td>
                <?php if($record->updated_datetime): ?>
                    <?=$record->updated_datetime->format($this->config()['myapp']['datetime_format'])?>
                <?php endif; ?>
            </td>
            <td><a href="/admin/<?=$this->routeName?>/form?id=<?=$record->id?>"><?=$this->icon('fa-pencil-square','fa-lg')?></a></td>
        </tr>
    <?php endforeach; ?>
</table>